# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: '#about'
    weight: 10
  - name: CV
    url: 'me/'
    weight: 20
  - name: Group
    url: 'group/'
    weight: 30
  # - name: Posts
    # url: 'post/'
    # weight: 35
  - name: Research
    url: 'projpage/'
    weight: 40
  - name: Publications
    url: 'publication/'
    weight: 50
  - name: Partnership
    url: 'partner/'
    weight: 75
  - name: Teaching
    url: 'courses/'
    weight: 60
  - name: Openings
    url: 'opening/'
    weight: 80

  # - name: Resources
    # url: 'resource/'
    # weight: 70
  # - name: Contact
    # url: 'contact/'
    # weight: 80


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
