# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 主页
    url: '#about'
    weight: 10
  #- name: 团队
  #  url: 'group/'
  #  weight: 30
 # - name: 贴文
  #  url: 'post/'
 #   weight: 35
  - name: 项目
    url: 'projpage/'
    weight: 40
  - name: 论文
    url: 'publipage/'
    weight: 50
  - name: 新闻
    url: 'news/'
    weight: 55
 # - name: 合作
  #  url: 'partner/'
  #  weight: 75
  - name: 课程
    url: 'courses/'
    weight: 60
  - name: 招募
    url: 'opening/'
    weight: 80
  - name: 研究中心
    url: 'center/'
    weight: 90
  

  #- name: 资源
 #   url: 'resource/'
 #   weight: 70
  # - name: 联系方式
    # url: 'contact/'
    # weight: 80
# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
